#pragma config(Sensor, S1,     Color,          sensorColorNxtFULL)
#pragma config(Sensor, S3,     Light,          sensorLightActive)
#pragma config(Sensor, S4,     Distance,       sensorSONAR)
#pragma config(Motor,  motorC,          Right,         tmotorNXT, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorB,          Left,          tmotorNXT, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
