#pragma config(UserModel, "H:/Users/Jim/Documents/TotalCanzRecall/TotalCanzRecallModel.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void displayColorSimple();
void displayRGBColorValues();


task main()
{
	while (1)
	{
		displayCenteredTextLine(1, "Floor Light Sensor");
		displayCenteredBigTextLine(2, "%d", SensorValue[Light]);
		displayCenteredTextLine(4, "Object Distance");
		displayCenteredBigTextLine(5, "%d", SensorValue[Distance]);
		//displayColorSimple();
  	wait1Msec(50);       // The program waits n milliseconds before running further code
	}
}


void displayColorSimple()
{
	eraseDisplay();
  displayCenteredTextLine(1, "Detected color:");

	// Check the detected colour and display the name of the
  // color in a large font on the screen.
  switch(SensorValue[Color])
  {
    case BLACKCOLOR:  displayCenteredBigTextLine(4, "Black");   break;
  	case BLUECOLOR:   displayCenteredBigTextLine(4, "Blue");    break;
    case GREENCOLOR:  displayCenteredBigTextLine(4, "Green");   break;
    case YELLOWCOLOR: displayCenteredBigTextLine(4, "Yellow");  break;
    case REDCOLOR:    displayCenteredBigTextLine(4, "Red");     break;
    case WHITECOLOR:  displayCenteredBigTextLine(4, "White");   break;
    default:          displayCenteredBigTextLine(4, "Unknown"); break;
  }
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                              displayColorIndex
//
// When in RGB mode, the sensor tries to dtect one of six reflected colors. This function displays the detected color
// on the NXT LCD.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



void displayColorIndex()
{
  string sColor;

  switch (SensorValue[Color])
  {
  case BLACKCOLOR:    sColor = "Black";     break;
  case BLUECOLOR:     sColor = "Blue";      break;
  case GREENCOLOR:    sColor = "Green";     break;
  case YELLOWCOLOR:   sColor = "Yellow";    break;
  case REDCOLOR:      sColor = "Red";       break;
  case WHITECOLOR:    sColor = "White";     break;
  default:            sColor = "???";       break;
  }
  displayCenteredTextLine(2, sColor);
}


/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                              displayRGBColorValues
//
// Displays all four possible color analog values on the NXT screen. The four values are:
//     Red          -- Analog value showing reflected light from Red   LED
//     Green        -- Analog value showing reflected light from Green LED
//     Blue         -- Analog value showing reflected light from Blue  LED
//     Ambient      -- No background LED turned on
//
// There are three numbers displayed for each color:
//     1. The raw analog value detected.
//     2. The "normalized" value detected. This is simply the raw value less the value of ambient light.
//     3. The "percentage" value detected. This is the "normalized" value scaled on a 0 to 100 (max value) scale.
//
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

void displayRGBColorValues()
{
	short nAtoDValues[4];
	short nRawValues[4];
	short nColorValues[4];
	string sTemp;

  displayCenteredBigTextLine(0, "RGB");
  getColorSensorData(Color, colorAtoD,   &nAtoDValues[0]);
  getColorSensorData(Color, colorRaw,    &nRawValues[0]);
  getColorSensorData(Color, colorValue,  &nColorValues[0]);

  displayColorIndex();

  displayTextLine(3, "   AtoD  Raw   %%");
  stringFormat(sTemp, "R  %4i%5i", nAtoDValues[0], nRawValues[0]);      displayTextLine(4, "%s%4i", sTemp, nColorValues[0]);
  stringFormat(sTemp, "G  %4i%5i", nAtoDValues[1], nRawValues[1]);      displayTextLine(5, "%s%4i", sTemp, nColorValues[1]);
  stringFormat(sTemp, "B  %4i%5i", nAtoDValues[2], nRawValues[2]);      displayTextLine(6, "%s%4i", sTemp, nColorValues[2]);
  stringFormat(sTemp, "Amb%4i%5i", nAtoDValues[3], nRawValues[3]);      displayTextLine(7, "%s%4i", sTemp, nColorValues[3]);
}
